language: node_js
node_js:
  - "8"
  - "10"
  - "12"
cache:
  directories:
    - "node_modules"
before_script:
  - npm run fix
  - npm run version
  - npm run build
script:
  - node_version=$(node -v); if [ ${node_version:1:2} = 12 ]; then npm run test:coveralls; else npm run test; fi
deploy:
  provider: npm
  skip-cleanup: true
  email: "$AUTH_EMAIL"
  api_key: "$AUTH_TOKEN"
  on:
    branch: master
    node: 12
